[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# 08:00 Africa/Luanda = 07:00 UTC
[[scheduled.functions]]
  name = "daily"
  cron = "0 7 * * *"
