[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  external_node_modules = ["@sendgrid/mail", "twilio"]

# 07:00 UTC = 08:00 Africa/Luanda
[[scheduled.functions]]
  name = "daily"
  cron = "0 7 * * *"
